# -*- coding: utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
# http://doc.scrapy.org/en/latest/topics/items.html

import scrapy


class ScrapybotsItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    LISTING_DETAIL_PAGE_URL         = scrapy.Field()
########################################### GENERAL ITEM FIELDS ########################################################
    #Site specific item fields
    AGENT_NAME                      = scrapy.Field()
    AGENT_MOBILE                    = scrapy.Field()
    AGENT_EMAIL_ADDRESS             = scrapy.Field()
    COMPANY_NAME                    = scrapy.Field()
    COMPANY_ADDRESS                 = scrapy.Field()
    CITY_OPERATING                  = scrapy.Field()
    AREAS_OPERATING                 = scrapy.Field()
    PROFILE_PICTURE_URL             = scrapy.Field()
    DATE_OF_REGISTRATION            = scrapy.Field()
    SPECIALIZED_IN                  = scrapy.Field()
    WEBSITE_LINK                    = scrapy.Field()
    REVIEWS                         = scrapy.Field()
    LISTING_IN_SALE                 = scrapy.Field()
    LISTING_IN_RENT                 = scrapy.Field()
    BUILDERS_OPERATING_WITH         = scrapy.Field()
    PRICE_RANGE_OF_LISTINGS         = scrapy.Field()
    CERTIFICATION_BY_SITE           = scrapy.Field()
    DATE_OF_LAST_POSTING            = scrapy.Field()
    LISTING_IN_RESALE               = scrapy.Field()
    NUMBER_OF_EMPLOYEES_LISTED      = scrapy.Field()
    SELLER_CATEGORY                 = scrapy.Field()
    PROPERTY_CATEGORY               = scrapy.Field()
    IMAGES_PER_LISTING              = scrapy.Field()
    VIDEOS_PER_LISTING              = scrapy.Field()
    VIEW_360_FEATURE                = scrapy.Field()
    COMPANY_CONTACT_NO              = scrapy.Field()
    YEAR_OF_ESTABLISHMENT           = scrapy.Field()
    MIN_PRICE                       = scrapy.Field()
    MAX_PRICE                       = scrapy.Field()
    LISTING_STATUS                  = scrapy.Field()
    IMPRESSIONS                     = scrapy.Field()
    CTR                             = scrapy.Field()

    # Fields scraped from listing pages of magicbricks.com
    AGENT_ID                        = scrapy.Field()
    NUMBER_OF_LISTING               = scrapy.Field()
    IS_AGENT_VERIFIED               = scrapy.Field()
    IS_LISTING_VERIFIED             = scrapy.Field()
    LISTING_ID                      = scrapy.Field()
    LISTING_TITLE                   = scrapy.Field()
    LISTING_PRICE                   = scrapy.Field()
    LISTING_POSTED_ON               = scrapy.Field()
    LISTING_LOCATION                = scrapy.Field()
    LISTING_AMENITIES               = scrapy.Field()
    LISTING_IMAGE_URL               = scrapy.Field()
    LISTING_TRANSACTION_TYPE        = scrapy.Field()
    PROPERTY_AGE                    = scrapy.Field()
    LISTING_CITY                    = scrapy.Field()
    LISTING_CATEGORY                = scrapy.Field()
    LISTING_DETAILS                 = scrapy.Field()
    LISTING_DESCRIPTION             = scrapy.Field()
    PROPERTY_AREA                   = scrapy.Field()
    PROPERTY_RATE_PER_SQ_FT         = scrapy.Field()
    LISTING_CITY_ID                 = scrapy.Field()
    LISTING_URL                     = scrapy.Field()
    LATITUDE                        = scrapy.Field()
    LONGITUDE                       = scrapy.Field()
    ZOOM_LEVEL                      = scrapy.Field()
    GEO_COORDINATES                 = scrapy.Field()
    LISTING_LOCALITY                = scrapy.Field()
    LISTING_LOCALITY_ID             = scrapy.Field()
    FLOOR_NUMBER                    = scrapy.Field()
    FURNISHED_STATUS                = scrapy.Field()
    PROPERTY_NAME                   = scrapy.Field()
    PROJECT_NAME                    = scrapy.Field()
    LISTING_ADDRESS                 = scrapy.Field()

# IREF ITEMS
    THREAD_TITLE                    = scrapy.Field()
    LAST_POSTED_IN_THREAD           = scrapy.Field()
    REPLIES_IN_THREAD               = scrapy.Field()
    TOTAL_VIEWS                     = scrapy.Field()
    FORUM_NAME                      = scrapy.Field()
    FIRST_POST_DATE                 = scrapy.Field()
    FIRST_POST_HEADING              = scrapy.Field()
    FIRST_POST_CONTENT              = scrapy.Field()

#MB FORUMS
    FORUM_QUESTION                  = scrapy.Field()
    FORUM_ANSWER                    = scrapy.Field()
    DATE                            = scrapy.Field()
    FORUM_SECTION                   = scrapy.Field()
    CITY                            = scrapy.Field()

#NN FORUMS
    COMPLETE_THREAD                 = scrapy.Field()
    NEXT_DEPTH_PAGE_URL             = scrapy.Field()




    PROJECT_ID                      = scrapy.Field()
    LINK                            = scrapy.Field()
    PRICE_RANGE                     = scrapy.Field()
    IMAGE_URL                       = scrapy.Field()
    BUILDER_ID                      = scrapy.Field()
    BUILDING_ID                     = scrapy.Field()
    START_DATE                      = scrapy.Field()
    POSSESSION_DATE                 = scrapy.Field()
    PROPERTY_COUNT                  = scrapy.Field()
    POSSESSION_TYPE                 = scrapy.Field()
    LOGO                            = scrapy.Field()
    BUILDER_NAME                    = scrapy.Field()
    MIN_AREA                        = scrapy.Field()
    MAX_AREA                        = scrapy.Field()
    MIN_BEDROOM                     = scrapy.Field()
    MAX_BEDROOM                     = scrapy.Field()
    BUILDER_URL                     = scrapy.Field()
    IMAGES_COUNT                    = scrapy.Field()
    VIDEOS_COUNT                    = scrapy.Field()
    FLOOR_IMAGES_COUNT              = scrapy.Field()
    CONSTRUCTION_IMAGE_COUNT        = scrapy.Field()
    VIDEO_URL                       = scrapy.Field()

    product_title                   = scrapy.Field()
    product_price                   = scrapy.Field()
    product_mrp                     = scrapy.Field()
    discount_percentage             = scrapy.Field()
    ratings_count                   = scrapy.Field()
    product_rating                  = scrapy.Field()
    thumb_images                    = scrapy.Field()
    product_images                  = scrapy.Field()
    review_title                    = scrapy.Field()
    review                          = scrapy.Field()
    review_posted_date              = scrapy.Field()
    available_sizes                 = scrapy.Field()
    shipping_charges                = scrapy.Field()
    seller_name                     = scrapy.Field()
    seller_rating                   = scrapy.Field()
    gender                          = scrapy.Field()
    product_subcategory             = scrapy.Field()
    is_cod_available                = scrapy.Field()
    return_time                     = scrapy.Field()
    delivery_time                   = scrapy.Field()
    image_urls                      = scrapy.Field()
    images                          = scrapy.Field()
    product_images_paths            = scrapy.Field()
    thumb_images_paths              = scrapy.Field()
    product_url                     = scrapy.Field()

    LOCALITY                        = scrapy.Field()
    CITY                            = scrapy.Field()
    FLOORS                          = scrapy.Field()
    TOTAL_AREA                      = scrapy.Field()
    OPEN_AREA                       = scrapy.Field()
    BHK_CONFIG                      = scrapy.Field()
    CARPET_AREA                     = scrapy.Field()
    DESCRIPTION                     = scrapy.Field()
    BANK_APPROVALS                  = scrapy.Field()
    VIEWS_COUNT                     = scrapy.Field()
    PRICE_APPRECIATION              = scrapy.Field()
    FIRST_APPRECIATION_DATE         = scrapy.Field()
    FLOOR_PLANS_COUNT               = scrapy.Field()
    TOWER_AND_UNITS                 = scrapy.Field()
    PROJECT_SPECIFICATIONS          = scrapy.Field()
    RES_OR_COM                      = scrapy.Field()
    PROJECT_ADDRESS                 = scrapy.Field()
    BASIC_AMENITIES                 = scrapy.Field()
    LIFESTYLE_AMENITIES             = scrapy.Field()
    BROCHURE_LINK                   = scrapy.Field()
    PROJECT_RATING                  = scrapy.Field()
    YEARS_OF_EXPERIENCE             = scrapy.Field()
    TOTAL_PROJECTS                  = scrapy.Field()
    ONGOING_PROJECTS                = scrapy.Field()
    BUILDER_LOGO                    = scrapy.Field()
    BUILDER_DESCRIPTION             = scrapy.Field()
    URL                             = scrapy.Field()
    PRICE_WITH_AREA                 = scrapy.Field()
    BEDROOMS                        = scrapy.Field()
    FLOORING_SPECIFICATIONS         = scrapy.Field()
    FITTING_SPECIFICATIONS          = scrapy.Field()
    WALLS_SPECIFICATIONS            = scrapy.Field()
    PROJECT_URL                     = scrapy.Field()


